# Generated by Django 3.1.4 on 2021-01-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShett',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem1', models.CharField(max_length=20)),
                ('mem2', models.CharField(max_length=20)),
                ('mem3', models.CharField(max_length=20)),
                ('mem4', models.CharField(max_length=20)),
                ('mem5', models.CharField(max_length=20)),
            ],
        ),
    ]
