# Generated by Django 3.1.4 on 2021-01-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkShett',
        ),
    ]
