# Generated by Django 3.1.4 on 2021-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
